name: Docker Image CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build image
        run: make image

      - name: Push image
        if: ${{ github.ref_name == 'master' }}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: make push-to-ghcr
